export type FunctionCategory =
  | "String"
  | "Numeric"
  | "Date & Time"
  | "Aggregate"
  | "Window"
  | "Control Flow"
  | "JSON"
  | "Cast"
  | "Encryption"
  | "Information";

export interface MysqlFunction {
  name: string;
  category: FunctionCategory;
  syntax: string;
  description: string;
  example: string;
  result?: string;
  /** Extra search terms — things you'd google instead of the function name. */
  aliases?: string[];
}

const DOC_PAGES: Record<FunctionCategory, string> = {
  String: "string-functions.html",
  Numeric: "mathematical-functions.html",
  "Date & Time": "date-and-time-functions.html",
  Aggregate: "aggregate-functions.html",
  Window: "window-function-descriptions.html",
  "Control Flow": "flow-control-functions.html",
  JSON: "json-functions.html",
  Cast: "cast-functions.html",
  Encryption: "encryption-functions.html",
  Information: "information-functions.html",
};

/** MySQL anchors are `#function_substring`; window functions use hyphens (`#function_row-number`). */
export function docUrl(fn: MysqlFunction): string {
  const slug = fn.name.toLowerCase().replace(/[^a-z0-9_]/g, "");
  const anchor = fn.category === "Window" ? slug.replace(/_/g, "-") : slug;
  return `https://dev.mysql.com/doc/refman/8.4/en/${DOC_PAGES[fn.category]}#function_${anchor}`;
}

export const MYSQL_FUNCTIONS: MysqlFunction[] = [
  // ---------------------------------------------------------------- String
  {
    name: "CONCAT",
    category: "String",
    syntax: "CONCAT(str1, str2, ...)",
    description: "Joins arguments into one string. Returns NULL if any argument is NULL.",
    example: "SELECT CONCAT('foo', '-', 'bar');",
    result: "'foo-bar'",
    aliases: ["join strings", "append", "+"],
  },
  {
    name: "CONCAT_WS",
    category: "String",
    syntax: "CONCAT_WS(separator, str1, str2, ...)",
    description: "Concatenates with a separator between each value. Skips NULL arguments (unlike CONCAT).",
    example: "SELECT CONCAT_WS(', ', 'Smith', NULL, 'Jane');",
    result: "'Smith, Jane'",
    aliases: ["join with separator", "implode"],
  },
  {
    name: "SUBSTRING",
    category: "String",
    syntax: "SUBSTRING(str, pos)\nSUBSTRING(str, pos, len)\nSUBSTRING(str FROM pos FOR len)",
    description: "Extracts a substring starting at pos (1-indexed). A negative pos counts from the end. Omit len to take the rest of the string.",
    example: "SELECT SUBSTRING('Quadratically', 5, 6);",
    result: "'ratica'",
    aliases: ["substr", "mid", "slice", "cut string"],
  },
  {
    name: "SUBSTRING_INDEX",
    category: "String",
    syntax: "SUBSTRING_INDEX(str, delim, count)",
    description: "Returns the part of str before count occurrences of delim. A negative count counts from the right.",
    example: "SELECT SUBSTRING_INDEX('a.b.c.d', '.', 2);",
    result: "'a.b'",
    aliases: ["split", "explode", "before delimiter"],
  },
  {
    name: "LEFT",
    category: "String",
    syntax: "LEFT(str, len)",
    description: "Returns the leftmost len characters.",
    example: "SELECT LEFT('foobarbar', 5);",
    result: "'fooba'",
  },
  {
    name: "RIGHT",
    category: "String",
    syntax: "RIGHT(str, len)",
    description: "Returns the rightmost len characters.",
    example: "SELECT RIGHT('foobarbar', 4);",
    result: "'rbar'",
  },
  {
    name: "LENGTH",
    category: "String",
    syntax: "LENGTH(str)",
    description: "Length of the string in BYTES. For multi-byte charsets this differs from CHAR_LENGTH.",
    example: "SELECT LENGTH('café');",
    result: "5 (utf8mb4)",
    aliases: ["size", "octet_length"],
  },
  {
    name: "CHAR_LENGTH",
    category: "String",
    syntax: "CHAR_LENGTH(str)",
    description: "Length of the string in CHARACTERS. This is usually what you want for user-facing lengths.",
    example: "SELECT CHAR_LENGTH('café');",
    result: "4",
    aliases: ["character_length", "count characters"],
  },
  {
    name: "LOWER",
    category: "String",
    syntax: "LOWER(str)",
    description: "Converts to lowercase. Alias: LCASE.",
    example: "SELECT LOWER('QUADRATICALLY');",
    result: "'quadratically'",
    aliases: ["lcase", "lowercase"],
  },
  {
    name: "UPPER",
    category: "String",
    syntax: "UPPER(str)",
    description: "Converts to uppercase. Alias: UCASE.",
    example: "SELECT UPPER('Hej');",
    result: "'HEJ'",
    aliases: ["ucase", "uppercase"],
  },
  {
    name: "TRIM",
    category: "String",
    syntax: "TRIM([{BOTH | LEADING | TRAILING} [remstr] FROM] str)\nTRIM(remstr FROM str)",
    description: "Removes leading and/or trailing characters (spaces by default).",
    example: "SELECT TRIM(LEADING 'x' FROM 'xxxbarxxx');",
    result: "'barxxx'",
    aliases: ["strip", "whitespace"],
  },
  {
    name: "LTRIM",
    category: "String",
    syntax: "LTRIM(str)",
    description: "Removes leading spaces.",
    example: "SELECT LTRIM('  barbar');",
    result: "'barbar'",
  },
  {
    name: "RTRIM",
    category: "String",
    syntax: "RTRIM(str)",
    description: "Removes trailing spaces.",
    example: "SELECT RTRIM('barbar   ');",
    result: "'barbar'",
  },
  {
    name: "REPLACE",
    category: "String",
    syntax: "REPLACE(str, from_str, to_str)",
    description: "Replaces every occurrence of from_str with to_str. Case-sensitive.",
    example: "SELECT REPLACE('www.mysql.com', 'w', 'Ww');",
    result: "'WwWwWw.mysql.com'",
    aliases: ["find and replace", "swap"],
  },
  {
    name: "REVERSE",
    category: "String",
    syntax: "REVERSE(str)",
    description: "Returns the string with characters in reverse order.",
    example: "SELECT REVERSE('abc');",
    result: "'cba'",
  },
  {
    name: "LPAD",
    category: "String",
    syntax: "LPAD(str, len, padstr)",
    description: "Left-pads str with padstr to length len. Truncates if str is longer than len.",
    example: "SELECT LPAD('7', 3, '0');",
    result: "'007'",
    aliases: ["zero pad", "leading zeros"],
  },
  {
    name: "RPAD",
    category: "String",
    syntax: "RPAD(str, len, padstr)",
    description: "Right-pads str with padstr to length len.",
    example: "SELECT RPAD('hi', 5, '?');",
    result: "'hi???'",
  },
  {
    name: "LOCATE",
    category: "String",
    syntax: "LOCATE(substr, str)\nLOCATE(substr, str, pos)",
    description: "Position of the first occurrence of substr (1-indexed), or 0 if not found. Note the argument order is the reverse of INSTR.",
    example: "SELECT LOCATE('bar', 'foobarbar');",
    result: "4",
    aliases: ["indexof", "find position", "search"],
  },
  {
    name: "INSTR",
    category: "String",
    syntax: "INSTR(str, substr)",
    description: "Position of the first occurrence of substr, or 0 if not found. Same as LOCATE but with the arguments swapped.",
    example: "SELECT INSTR('foobarbar', 'bar');",
    result: "4",
    aliases: ["indexof", "contains", "find position"],
  },
  {
    name: "POSITION",
    category: "String",
    syntax: "POSITION(substr IN str)",
    description: "Standard-SQL synonym for LOCATE(substr, str).",
    example: "SELECT POSITION('bar' IN 'foobar');",
    result: "4",
  },
  {
    name: "REPEAT",
    category: "String",
    syntax: "REPEAT(str, count)",
    description: "Repeats str count times. Returns '' if count <= 0.",
    example: "SELECT REPEAT('ab', 3);",
    result: "'ababab'",
  },
  {
    name: "SPACE",
    category: "String",
    syntax: "SPACE(N)",
    description: "Returns a string of N spaces.",
    example: "SELECT CONCAT('a', SPACE(3), 'b');",
    result: "'a   b'",
  },
  {
    name: "INSERT",
    category: "String",
    syntax: "INSERT(str, pos, len, newstr)",
    description: "Replaces len characters of str starting at pos with newstr. (The string function, not the statement.)",
    example: "SELECT INSERT('Quadratic', 3, 4, 'What');",
    result: "'QuWhattic'",
    aliases: ["splice", "overwrite"],
  },
  {
    name: "ELT",
    category: "String",
    syntax: "ELT(N, str1, str2, ...)",
    description: "Returns the Nth argument (1-indexed), or NULL if N is out of range.",
    example: "SELECT ELT(2, 'a', 'b', 'c');",
    result: "'b'",
    aliases: ["nth element", "pick"],
  },
  {
    name: "FIELD",
    category: "String",
    syntax: "FIELD(str, val1, val2, ...)",
    description: "Index (1-based) of str in the list, 0 if not found. Handy for custom ORDER BY sorts.",
    example: "SELECT FIELD('b', 'a', 'b', 'c');",
    result: "2",
    aliases: ["custom sort order", "order by list"],
  },
  {
    name: "FIND_IN_SET",
    category: "String",
    syntax: "FIND_IN_SET(str, strlist)",
    description: "Position of str within a comma-separated list, 0 if absent. Works with SET columns.",
    example: "SELECT FIND_IN_SET('b', 'a,b,c');",
    result: "2",
    aliases: ["in comma list", "csv contains"],
  },
  {
    name: "REGEXP_LIKE",
    category: "String",
    syntax: "REGEXP_LIKE(expr, pat[, match_type])",
    description: "Returns 1 if expr matches the regex pat. match_type: 'c' case-sensitive, 'i' case-insensitive, 'm' multi-line, 'n' . matches newline.",
    example: "SELECT REGEXP_LIKE('CamelCase', '^[A-Z]', 'c');",
    result: "1",
    aliases: ["regex", "rlike", "matches", "pattern"],
  },
  {
    name: "REGEXP_REPLACE",
    category: "String",
    syntax: "REGEXP_REPLACE(expr, pat, repl[, pos[, occurrence[, match_type]]])",
    description: "Replaces regex matches. Use $1, $2 in repl for capture groups. occurrence = 0 replaces all (default).",
    example: "SELECT REGEXP_REPLACE('a1b2', '[0-9]', '#');",
    result: "'a#b#'",
    aliases: ["regex replace", "preg_replace"],
  },
  {
    name: "REGEXP_SUBSTR",
    category: "String",
    syntax: "REGEXP_SUBSTR(expr, pat[, pos[, occurrence[, match_type]]])",
    description: "Returns the substring matching the regex, or NULL if there is no match.",
    example: "SELECT REGEXP_SUBSTR('id: 4821', '[0-9]+');",
    result: "'4821'",
    aliases: ["regex extract", "capture"],
  },
  {
    name: "REGEXP_INSTR",
    category: "String",
    syntax: "REGEXP_INSTR(expr, pat[, pos[, occurrence[, return_option[, match_type]]]])",
    description: "Position of the regex match, 0 if none. return_option 1 returns the position after the match.",
    example: "SELECT REGEXP_INSTR('abc123', '[0-9]+');",
    result: "4",
    aliases: ["regex position"],
  },
  {
    name: "STRCMP",
    category: "String",
    syntax: "STRCMP(expr1, expr2)",
    description: "Returns 0 if the strings are the same, -1 if the first is smaller, 1 otherwise.",
    example: "SELECT STRCMP('text', 'text2');",
    result: "-1",
    aliases: ["compare strings"],
  },
  {
    name: "SOUNDEX",
    category: "String",
    syntax: "SOUNDEX(str)",
    description: "Phonetic representation of the string — two similar-sounding words share a soundex string.",
    example: "SELECT SOUNDEX('Robert') = SOUNDEX('Rupert');",
    result: "1",
    aliases: ["fuzzy match", "sounds like", "phonetic"],
  },
  {
    name: "FORMAT",
    category: "String",
    syntax: "FORMAT(X, D[, locale])",
    description: "Formats a number to D decimals with thousands separators, returned as a string.",
    example: "SELECT FORMAT(12332.1234, 2);",
    result: "'12,332.12'",
    aliases: ["number_format", "thousands separator", "comma"],
  },
  {
    name: "QUOTE",
    category: "String",
    syntax: "QUOTE(str)",
    description: "Escapes a string for use as a SQL literal, wrapping it in single quotes.",
    example: "SELECT QUOTE('Don\\'t');",
    result: "'Don\\'t'",
    aliases: ["escape", "sanitize"],
  },
  {
    name: "HEX",
    category: "String",
    syntax: "HEX(str_or_num)",
    description: "Hexadecimal representation of a string or number.",
    example: "SELECT HEX('abc');",
    result: "'616263'",
  },
  {
    name: "UNHEX",
    category: "String",
    syntax: "UNHEX(str)",
    description: "Inverse of HEX — interprets each pair of hex digits as a byte.",
    example: "SELECT UNHEX('616263');",
    result: "'abc'",
  },
  {
    name: "TO_BASE64",
    category: "String",
    syntax: "TO_BASE64(str)",
    description: "Base-64 encodes the string.",
    example: "SELECT TO_BASE64('abc');",
    result: "'YWJj'",
    aliases: ["base64 encode"],
  },
  {
    name: "FROM_BASE64",
    category: "String",
    syntax: "FROM_BASE64(str)",
    description: "Decodes a base-64 string, returning a binary string.",
    example: "SELECT FROM_BASE64('YWJj');",
    result: "'abc'",
    aliases: ["base64 decode"],
  },
  {
    name: "ASCII",
    category: "String",
    syntax: "ASCII(str)",
    description: "Numeric value of the leftmost character, 0 for an empty string.",
    example: "SELECT ASCII('2');",
    result: "50",
    aliases: ["char code", "ord"],
  },
  {
    name: "CHAR",
    category: "String",
    syntax: "CHAR(N, ... [USING charset])",
    description: "Interprets each argument as an integer and returns the string made of those code points.",
    example: "SELECT CHAR(77, 121, 83, 81, 76);",
    result: "'MySQL'",
    aliases: ["chr", "from char code"],
  },
  {
    name: "ORD",
    category: "String",
    syntax: "ORD(str)",
    description: "Code for the leftmost character; multi-byte aware (unlike ASCII).",
    example: "SELECT ORD('2');",
    result: "50",
  },
  {
    name: "BIN",
    category: "String",
    syntax: "BIN(N)",
    description: "Binary-string representation of the number N.",
    example: "SELECT BIN(12);",
    result: "'1100'",
    aliases: ["binary"],
  },

  // --------------------------------------------------------------- Numeric
  {
    name: "ABS",
    category: "Numeric",
    syntax: "ABS(X)",
    description: "Absolute value.",
    example: "SELECT ABS(-32);",
    result: "32",
  },
  {
    name: "CEILING",
    category: "Numeric",
    syntax: "CEILING(X)  -- or CEIL(X)",
    description: "Smallest integer not less than X (rounds up).",
    example: "SELECT CEILING(1.23);",
    result: "2",
    aliases: ["ceil", "round up"],
  },
  {
    name: "FLOOR",
    category: "Numeric",
    syntax: "FLOOR(X)",
    description: "Largest integer not greater than X (rounds down).",
    example: "SELECT FLOOR(1.23);",
    result: "1",
    aliases: ["round down"],
  },
  {
    name: "ROUND",
    category: "Numeric",
    syntax: "ROUND(X)\nROUND(X, D)",
    description: "Rounds to D decimal places (0 by default). A negative D rounds to the left of the decimal point.",
    example: "SELECT ROUND(1.298, 1), ROUND(1234, -2);",
    result: "1.3, 1200",
    aliases: ["round to decimals", "2 decimal places"],
  },
  {
    name: "TRUNCATE",
    category: "Numeric",
    syntax: "TRUNCATE(X, D)",
    description: "Truncates X to D decimals WITHOUT rounding. D is required.",
    example: "SELECT TRUNCATE(1.999, 1);",
    result: "1.9",
    aliases: ["chop decimals", "no rounding"],
  },
  {
    name: "MOD",
    category: "Numeric",
    syntax: "MOD(N, M)  -- or N % M, N MOD M",
    description: "Remainder of N divided by M. Returns NULL if M is 0.",
    example: "SELECT MOD(234, 10);",
    result: "4",
    aliases: ["modulo", "remainder", "%"],
  },
  {
    name: "POW",
    category: "Numeric",
    syntax: "POW(X, Y)  -- or POWER(X, Y)",
    description: "X raised to the power of Y.",
    example: "SELECT POW(2, 10);",
    result: "1024",
    aliases: ["power", "exponent", "**"],
  },
  {
    name: "SQRT",
    category: "Numeric",
    syntax: "SQRT(X)",
    description: "Square root. Returns NULL for negative X.",
    example: "SELECT SQRT(16);",
    result: "4",
  },
  {
    name: "EXP",
    category: "Numeric",
    syntax: "EXP(X)",
    description: "e raised to the power of X.",
    example: "SELECT EXP(1);",
    result: "2.718281828459045",
  },
  {
    name: "LOG",
    category: "Numeric",
    syntax: "LOG(X)\nLOG(B, X)",
    description: "Natural log of X, or the log of X to base B with two arguments.",
    example: "SELECT LOG(2, 65536);",
    result: "16",
    aliases: ["logarithm", "ln"],
  },
  {
    name: "LOG10",
    category: "Numeric",
    syntax: "LOG10(X)",
    description: "Base-10 logarithm.",
    example: "SELECT LOG10(1000);",
    result: "3",
  },
  {
    name: "LOG2",
    category: "Numeric",
    syntax: "LOG2(X)",
    description: "Base-2 logarithm.",
    example: "SELECT LOG2(65536);",
    result: "16",
  },
  {
    name: "RAND",
    category: "Numeric",
    syntax: "RAND()\nRAND(N)",
    description: "Random float in [0, 1). Pass a seed N for a repeatable sequence. ORDER BY RAND() shuffles rows (slow on big tables).",
    example: "SELECT FLOOR(1 + RAND() * 6);",
    result: "random 1–6",
    aliases: ["random", "shuffle", "sample"],
  },
  {
    name: "SIGN",
    category: "Numeric",
    syntax: "SIGN(X)",
    description: "Returns -1, 0, or 1 depending on the sign of X.",
    example: "SELECT SIGN(-32);",
    result: "-1",
  },
  {
    name: "GREATEST",
    category: "Numeric",
    syntax: "GREATEST(value1, value2, ...)",
    description: "Largest of the arguments. Returns NULL if any argument is NULL. (Row-wise, unlike MAX.)",
    example: "SELECT GREATEST(2, 0, 34);",
    result: "34",
    aliases: ["max of columns", "largest"],
  },
  {
    name: "LEAST",
    category: "Numeric",
    syntax: "LEAST(value1, value2, ...)",
    description: "Smallest of the arguments. Returns NULL if any argument is NULL. (Row-wise, unlike MIN.)",
    example: "SELECT LEAST(2, 0, 34);",
    result: "0",
    aliases: ["min of columns", "smallest"],
  },
  {
    name: "PI",
    category: "Numeric",
    syntax: "PI()",
    description: "The value of π.",
    example: "SELECT PI();",
    result: "3.141593",
  },
  {
    name: "DEGREES",
    category: "Numeric",
    syntax: "DEGREES(X)",
    description: "Converts radians to degrees.",
    example: "SELECT DEGREES(PI());",
    result: "180",
  },
  {
    name: "RADIANS",
    category: "Numeric",
    syntax: "RADIANS(X)",
    description: "Converts degrees to radians.",
    example: "SELECT RADIANS(90);",
    result: "1.5707963267948966",
  },
  {
    name: "CRC32",
    category: "Numeric",
    syntax: "CRC32(expr)",
    description: "Cyclic redundancy check value as a 32-bit unsigned integer. Useful as a cheap hash for bucketing.",
    example: "SELECT CRC32('MySQL');",
    result: "3259397556",
    aliases: ["checksum", "hash bucket"],
  },

  // ----------------------------------------------------------- Date & Time
  {
    name: "NOW",
    category: "Date & Time",
    syntax: "NOW([fsp])",
    description: "Current date and time. Constant within a single statement. Pass fsp (0–6) for fractional seconds.",
    example: "SELECT NOW(), NOW(3);",
    result: "'2026-07-13 09:14:02'",
    aliases: ["current_timestamp", "localtime", "today", "timestamp"],
  },
  {
    name: "SYSDATE",
    category: "Date & Time",
    syntax: "SYSDATE([fsp])",
    description: "Time at which the function executes — unlike NOW(), it changes within a statement.",
    example: "SELECT SYSDATE();",
    result: "'2026-07-13 09:14:02'",
  },
  {
    name: "CURDATE",
    category: "Date & Time",
    syntax: "CURDATE()",
    description: "Current date, no time part. Alias: CURRENT_DATE.",
    example: "SELECT CURDATE();",
    result: "'2026-07-13'",
    aliases: ["current_date", "today"],
  },
  {
    name: "CURTIME",
    category: "Date & Time",
    syntax: "CURTIME([fsp])",
    description: "Current time of day. Alias: CURRENT_TIME.",
    example: "SELECT CURTIME();",
    result: "'09:14:02'",
    aliases: ["current_time"],
  },
  {
    name: "UNIX_TIMESTAMP",
    category: "Date & Time",
    syntax: "UNIX_TIMESTAMP()\nUNIX_TIMESTAMP(date)",
    description: "Seconds since the epoch. With no argument, uses the current time.",
    example: "SELECT UNIX_TIMESTAMP('2026-07-13 00:00:00');",
    result: "1784332800",
    aliases: ["epoch", "unix time", "to timestamp"],
  },
  {
    name: "FROM_UNIXTIME",
    category: "Date & Time",
    syntax: "FROM_UNIXTIME(unix_timestamp)\nFROM_UNIXTIME(unix_timestamp, format)",
    description: "Converts an epoch value to a datetime, optionally formatted with DATE_FORMAT specifiers.",
    example: "SELECT FROM_UNIXTIME(1784332800);",
    result: "'2026-07-13 00:00:00'",
    aliases: ["epoch to date", "unix to datetime"],
  },
  {
    name: "DATE_FORMAT",
    category: "Date & Time",
    syntax: "DATE_FORMAT(date, format)",
    description:
      "Formats a date. Common specifiers: %Y 4-digit year, %y 2-digit, %m month 01–12, %c month 1–12, %M month name, %b abbrev month, %d day 01–31, %e day 1–31, %D day with suffix, %W weekday name, %a abbrev weekday, %H hour 00–23, %h hour 01–12, %i minutes, %s seconds, %p AM/PM, %j day of year, %%  literal %.",
    example: "SELECT DATE_FORMAT(NOW(), '%W, %M %e, %Y');",
    result: "'Monday, July 13, 2026'",
    aliases: ["format date", "strftime", "pretty date"],
  },
  {
    name: "STR_TO_DATE",
    category: "Date & Time",
    syntax: "STR_TO_DATE(str, format)",
    description: "Parses a string into a date using DATE_FORMAT specifiers — the inverse of DATE_FORMAT.",
    example: "SELECT STR_TO_DATE('13/07/2026', '%d/%m/%Y');",
    result: "'2026-07-13'",
    aliases: ["parse date", "string to date"],
  },
  {
    name: "DATE_ADD",
    category: "Date & Time",
    syntax: "DATE_ADD(date, INTERVAL expr unit)",
    description:
      "Adds an interval. Units: MICROSECOND, SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, QUARTER, YEAR, and compounds like SECOND_MICROSECOND, DAY_HOUR, YEAR_MONTH.",
    example: "SELECT DATE_ADD('2026-01-31', INTERVAL 1 MONTH);",
    result: "'2026-02-28'",
    aliases: ["add days", "adddate", "plus interval", "date math"],
  },
  {
    name: "DATE_SUB",
    category: "Date & Time",
    syntax: "DATE_SUB(date, INTERVAL expr unit)",
    description: "Subtracts an interval from a date. Same units as DATE_ADD.",
    example: "SELECT DATE_SUB(NOW(), INTERVAL 7 DAY);",
    result: "one week ago",
    aliases: ["subtract days", "subdate", "minus interval", "last 30 days"],
  },
  {
    name: "DATEDIFF",
    category: "Date & Time",
    syntax: "DATEDIFF(expr1, expr2)",
    description: "Days from expr2 to expr1 (expr1 - expr2). Only the date parts are compared.",
    example: "SELECT DATEDIFF('2026-07-13', '2026-07-01');",
    result: "12",
    aliases: ["days between", "date difference"],
  },
  {
    name: "TIMESTAMPDIFF",
    category: "Date & Time",
    syntax: "TIMESTAMPDIFF(unit, start, end)",
    description: "Difference between two datetimes in the given unit (end - start). Note the argument order is the reverse of DATEDIFF.",
    example: "SELECT TIMESTAMPDIFF(YEAR, '1994-06-15', CURDATE());",
    result: "32 (age in years)",
    aliases: ["age", "months between", "hours between", "difference"],
  },
  {
    name: "TIMESTAMPADD",
    category: "Date & Time",
    syntax: "TIMESTAMPADD(unit, interval, datetime_expr)",
    description: "Adds interval (in unit) to a datetime.",
    example: "SELECT TIMESTAMPADD(MINUTE, 90, '2026-07-13 08:00:00');",
    result: "'2026-07-13 09:30:00'",
  },
  {
    name: "TIMEDIFF",
    category: "Date & Time",
    syntax: "TIMEDIFF(expr1, expr2)",
    description: "expr1 - expr2 expressed as a TIME value. Both arguments must be the same type.",
    example: "SELECT TIMEDIFF('10:00:00', '08:30:00');",
    result: "'01:30:00'",
  },
  {
    name: "EXTRACT",
    category: "Date & Time",
    syntax: "EXTRACT(unit FROM date)",
    description: "Pulls a single part out of a date. Same units as DATE_ADD.",
    example: "SELECT EXTRACT(YEAR_MONTH FROM '2026-07-13');",
    result: "202607",
    aliases: ["date part", "get year", "get month"],
  },
  {
    name: "DATE",
    category: "Date & Time",
    syntax: "DATE(expr)",
    description: "Extracts the date part of a datetime, dropping the time. Beware: DATE(col) in a WHERE clause defeats the index on col.",
    example: "SELECT DATE('2026-07-13 09:14:02');",
    result: "'2026-07-13'",
    aliases: ["strip time", "date only"],
  },
  {
    name: "TIME",
    category: "Date & Time",
    syntax: "TIME(expr)",
    description: "Extracts the time part of a datetime.",
    example: "SELECT TIME('2026-07-13 09:14:02');",
    result: "'09:14:02'",
  },
  {
    name: "YEAR",
    category: "Date & Time",
    syntax: "YEAR(date)",
    description: "Year as a number (1000–9999), or NULL for the zero date.",
    example: "SELECT YEAR('2026-07-13');",
    result: "2026",
  },
  {
    name: "MONTH",
    category: "Date & Time",
    syntax: "MONTH(date)",
    description: "Month number, 1–12.",
    example: "SELECT MONTH('2026-07-13');",
    result: "7",
  },
  {
    name: "DAY",
    category: "Date & Time",
    syntax: "DAY(date)  -- or DAYOFMONTH(date)",
    description: "Day of the month, 1–31.",
    example: "SELECT DAY('2026-07-13');",
    result: "13",
    aliases: ["dayofmonth"],
  },
  {
    name: "HOUR",
    category: "Date & Time",
    syntax: "HOUR(time)",
    description: "Hour. For TIME values the range can exceed 23.",
    example: "SELECT HOUR('09:14:02');",
    result: "9",
  },
  {
    name: "MINUTE",
    category: "Date & Time",
    syntax: "MINUTE(time)",
    description: "Minute, 0–59.",
    example: "SELECT MINUTE('09:14:02');",
    result: "14",
  },
  {
    name: "SECOND",
    category: "Date & Time",
    syntax: "SECOND(time)",
    description: "Second, 0–59.",
    example: "SELECT SECOND('09:14:02');",
    result: "2",
  },
  {
    name: "DAYOFWEEK",
    category: "Date & Time",
    syntax: "DAYOFWEEK(date)",
    description: "Weekday index, 1 = Sunday … 7 = Saturday (ODBC standard). Compare with WEEKDAY, which is 0 = Monday.",
    example: "SELECT DAYOFWEEK('2026-07-13');",
    result: "2 (Monday)",
  },
  {
    name: "WEEKDAY",
    category: "Date & Time",
    syntax: "WEEKDAY(date)",
    description: "Weekday index, 0 = Monday … 6 = Sunday.",
    example: "SELECT WEEKDAY('2026-07-13');",
    result: "0 (Monday)",
  },
  {
    name: "DAYNAME",
    category: "Date & Time",
    syntax: "DAYNAME(date)",
    description: "Name of the weekday.",
    example: "SELECT DAYNAME('2026-07-13');",
    result: "'Monday'",
  },
  {
    name: "MONTHNAME",
    category: "Date & Time",
    syntax: "MONTHNAME(date)",
    description: "Name of the month.",
    example: "SELECT MONTHNAME('2026-07-13');",
    result: "'July'",
  },
  {
    name: "DAYOFYEAR",
    category: "Date & Time",
    syntax: "DAYOFYEAR(date)",
    description: "Day of the year, 1–366.",
    example: "SELECT DAYOFYEAR('2026-07-13');",
    result: "194",
  },
  {
    name: "WEEK",
    category: "Date & Time",
    syntax: "WEEK(date[, mode])",
    description: "Week number. mode (0–7) controls whether weeks start Sunday or Monday and how week 1 is defined. Mode 3 gives ISO weeks.",
    example: "SELECT WEEK('2026-07-13', 3);",
    result: "29",
    aliases: ["week number", "iso week", "yearweek"],
  },
  {
    name: "QUARTER",
    category: "Date & Time",
    syntax: "QUARTER(date)",
    description: "Quarter of the year, 1–4.",
    example: "SELECT QUARTER('2026-07-13');",
    result: "3",
  },
  {
    name: "LAST_DAY",
    category: "Date & Time",
    syntax: "LAST_DAY(date)",
    description: "Last day of the month for the given date — the standard trick for month-end boundaries.",
    example: "SELECT LAST_DAY('2026-02-05');",
    result: "'2026-02-28'",
    aliases: ["end of month", "month end"],
  },
  {
    name: "MAKEDATE",
    category: "Date & Time",
    syntax: "MAKEDATE(year, dayofyear)",
    description: "Builds a date from a year and a day-of-year.",
    example: "SELECT MAKEDATE(2026, 194);",
    result: "'2026-07-13'",
  },
  {
    name: "MAKETIME",
    category: "Date & Time",
    syntax: "MAKETIME(hour, minute, second)",
    description: "Builds a TIME value from its parts.",
    example: "SELECT MAKETIME(12, 15, 30);",
    result: "'12:15:30'",
  },
  {
    name: "SEC_TO_TIME",
    category: "Date & Time",
    syntax: "SEC_TO_TIME(seconds)",
    description: "Converts a number of seconds into a TIME (HH:MM:SS).",
    example: "SELECT SEC_TO_TIME(5400);",
    result: "'01:30:00'",
    aliases: ["seconds to duration", "format duration"],
  },
  {
    name: "TIME_TO_SEC",
    category: "Date & Time",
    syntax: "TIME_TO_SEC(time)",
    description: "Converts a TIME into a number of seconds.",
    example: "SELECT TIME_TO_SEC('01:30:00');",
    result: "5400",
  },
  {
    name: "CONVERT_TZ",
    category: "Date & Time",
    syntax: "CONVERT_TZ(dt, from_tz, to_tz)",
    description: "Converts a datetime between time zones. Named zones ('US/Eastern') require the mysql time-zone tables to be loaded; offsets ('+00:00') always work.",
    example: "SELECT CONVERT_TZ('2026-07-13 12:00:00', '+00:00', '-04:00');",
    result: "'2026-07-13 08:00:00'",
    aliases: ["timezone", "utc to local"],
  },
  {
    name: "UTC_TIMESTAMP",
    category: "Date & Time",
    syntax: "UTC_TIMESTAMP([fsp])",
    description: "Current UTC date and time.",
    example: "SELECT UTC_TIMESTAMP();",
    result: "'2026-07-13 13:14:02'",
    aliases: ["utc now", "utc_date", "utc_time"],
  },

  // ------------------------------------------------------------- Aggregate
  {
    name: "COUNT",
    category: "Aggregate",
    syntax: "COUNT(*)\nCOUNT(expr)\nCOUNT(DISTINCT expr, ...)",
    description: "COUNT(*) counts rows; COUNT(expr) counts non-NULL values; COUNT(DISTINCT ...) counts distinct non-NULL values.",
    example: "SELECT COUNT(*), COUNT(DISTINCT user_id) FROM orders;",
    aliases: ["how many", "number of rows", "tally"],
  },
  {
    name: "SUM",
    category: "Aggregate",
    syntax: "SUM([DISTINCT] expr)",
    description: "Sum of the values. Returns NULL if there are no matching rows — wrap in COALESCE for 0.",
    example: "SELECT COALESCE(SUM(total), 0) FROM orders;",
    aliases: ["total", "add up"],
  },
  {
    name: "AVG",
    category: "Aggregate",
    syntax: "AVG([DISTINCT] expr)",
    description: "Mean of the values, ignoring NULLs.",
    example: "SELECT AVG(price) FROM products;",
    aliases: ["mean", "average"],
  },
  {
    name: "MIN",
    category: "Aggregate",
    syntax: "MIN([DISTINCT] expr)",
    description: "Smallest value in the group. For a row-wise minimum across columns use LEAST.",
    example: "SELECT MIN(created_at) FROM orders;",
    aliases: ["smallest", "earliest"],
  },
  {
    name: "MAX",
    category: "Aggregate",
    syntax: "MAX([DISTINCT] expr)",
    description: "Largest value in the group. For a row-wise maximum across columns use GREATEST.",
    example: "SELECT MAX(created_at) FROM orders;",
    aliases: ["largest", "latest", "most recent"],
  },
  {
    name: "GROUP_CONCAT",
    category: "Aggregate",
    syntax: "GROUP_CONCAT([DISTINCT] expr [ORDER BY ...] [SEPARATOR str])",
    description: "Concatenates values in a group into one string. Default separator is ','. Truncated at group_concat_max_len (1024 bytes by default!).",
    example: "SELECT user_id, GROUP_CONCAT(tag ORDER BY tag SEPARATOR ', ') FROM tags GROUP BY user_id;",
    aliases: ["string_agg", "implode group", "list of values", "comma separated"],
  },
  {
    name: "JSON_ARRAYAGG",
    category: "Aggregate",
    syntax: "JSON_ARRAYAGG(col_or_expr)",
    description: "Aggregates a group into a JSON array.",
    example: "SELECT user_id, JSON_ARRAYAGG(tag) FROM tags GROUP BY user_id;",
    result: "'[\"a\", \"b\"]'",
    aliases: ["group to json array"],
  },
  {
    name: "JSON_OBJECTAGG",
    category: "Aggregate",
    syntax: "JSON_OBJECTAGG(key, value)",
    description: "Aggregates key/value pairs in a group into a JSON object.",
    example: "SELECT JSON_OBJECTAGG(setting, value) FROM settings;",
    result: "'{\"theme\": \"dark\"}'",
    aliases: ["group to json object"],
  },
  {
    name: "STDDEV",
    category: "Aggregate",
    syntax: "STDDEV(expr)  -- population\nSTDDEV_SAMP(expr)  -- sample",
    description: "Standard deviation. STDDEV / STD / STDDEV_POP are the population form; STDDEV_SAMP is the sample form.",
    example: "SELECT STDDEV(score) FROM results;",
    aliases: ["std", "stddev_pop", "standard deviation"],
  },
  {
    name: "VARIANCE",
    category: "Aggregate",
    syntax: "VARIANCE(expr)  -- population\nVAR_SAMP(expr)  -- sample",
    description: "Variance. VARIANCE / VAR_POP are the population form; VAR_SAMP is the sample form.",
    example: "SELECT VARIANCE(score) FROM results;",
    aliases: ["var_pop", "var_samp"],
  },
  {
    name: "BIT_OR",
    category: "Aggregate",
    syntax: "BIT_OR(expr)\nBIT_AND(expr)\nBIT_XOR(expr)",
    description: "Bitwise OR / AND / XOR across all values in the group. Useful for collapsing flag columns.",
    example: "SELECT BIT_OR(flags) FROM permissions;",
    aliases: ["bit_and", "bit_xor", "bitwise", "flags"],
  },

  // ---------------------------------------------------------------- Window
  {
    name: "ROW_NUMBER",
    category: "Window",
    syntax: "ROW_NUMBER() OVER ([PARTITION BY ...] ORDER BY ...)",
    description: "Sequential number within the partition, starting at 1. Always distinct, even for ties.",
    example: "SELECT name, ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC) AS rn FROM staff;",
    aliases: ["rownum", "numbering", "top n per group", "deduplicate"],
  },
  {
    name: "RANK",
    category: "Window",
    syntax: "RANK() OVER ([PARTITION BY ...] ORDER BY ...)",
    description: "Rank with gaps — ties share a rank and the next rank skips ahead (1, 1, 3).",
    example: "SELECT name, RANK() OVER (ORDER BY score DESC) AS r FROM players;",
    aliases: ["ranking", "leaderboard"],
  },
  {
    name: "DENSE_RANK",
    category: "Window",
    syntax: "DENSE_RANK() OVER ([PARTITION BY ...] ORDER BY ...)",
    description: "Rank without gaps — ties share a rank and the next rank follows immediately (1, 1, 2).",
    example: "SELECT name, DENSE_RANK() OVER (ORDER BY score DESC) AS r FROM players;",
    aliases: ["ranking no gaps"],
  },
  {
    name: "LAG",
    category: "Window",
    syntax: "LAG(expr[, N[, default]]) OVER ([PARTITION BY ...] ORDER BY ...)",
    description: "Value from N rows before the current row (default N = 1). The classic way to diff a row against the previous one.",
    example: "SELECT day, total - LAG(total) OVER (ORDER BY day) AS delta FROM sales;",
    aliases: ["previous row", "difference from previous", "delta"],
  },
  {
    name: "LEAD",
    category: "Window",
    syntax: "LEAD(expr[, N[, default]]) OVER ([PARTITION BY ...] ORDER BY ...)",
    description: "Value from N rows after the current row.",
    example: "SELECT day, LEAD(total) OVER (ORDER BY day) AS next_total FROM sales;",
    aliases: ["next row"],
  },
  {
    name: "FIRST_VALUE",
    category: "Window",
    syntax: "FIRST_VALUE(expr) OVER ([PARTITION BY ...] ORDER BY ...)",
    description: "First value in the window frame.",
    example: "SELECT dept, FIRST_VALUE(name) OVER (PARTITION BY dept ORDER BY hired_at) FROM staff;",
    aliases: ["earliest per group"],
  },
  {
    name: "LAST_VALUE",
    category: "Window",
    syntax: "LAST_VALUE(expr) OVER (... ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)",
    description: "Last value in the frame. The default frame ends at the current row, so you almost always need an explicit frame clause.",
    example: "SELECT LAST_VALUE(price) OVER (ORDER BY day ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM ticks;",
    aliases: ["latest per group"],
  },
  {
    name: "NTILE",
    category: "Window",
    syntax: "NTILE(N) OVER ([PARTITION BY ...] ORDER BY ...)",
    description: "Splits the partition into N buckets and returns the bucket number of each row.",
    example: "SELECT name, NTILE(4) OVER (ORDER BY score) AS quartile FROM players;",
    aliases: ["quartile", "percentile bucket", "decile"],
  },
  {
    name: "PERCENT_RANK",
    category: "Window",
    syntax: "PERCENT_RANK() OVER ([PARTITION BY ...] ORDER BY ...)",
    description: "Relative rank from 0 to 1: (rank - 1) / (rows - 1).",
    example: "SELECT name, PERCENT_RANK() OVER (ORDER BY score) FROM players;",
    aliases: ["percentile"],
  },
  {
    name: "CUME_DIST",
    category: "Window",
    syntax: "CUME_DIST() OVER ([PARTITION BY ...] ORDER BY ...)",
    description: "Cumulative distribution: the fraction of rows at or below the current row.",
    example: "SELECT name, CUME_DIST() OVER (ORDER BY score) FROM players;",
    aliases: ["cumulative distribution"],
  },

  // ---------------------------------------------------------- Control Flow
  {
    name: "IF",
    category: "Control Flow",
    syntax: "IF(condition, value_if_true, value_if_false)",
    description: "Ternary conditional. (Not the same as the IF statement used in stored programs.)",
    example: "SELECT IF(stock > 0, 'in stock', 'sold out') FROM products;",
    aliases: ["ternary", "conditional", "iif"],
  },
  {
    name: "CASE",
    category: "Control Flow",
    syntax: "CASE value WHEN compare THEN result [...] [ELSE result] END\nCASE WHEN condition THEN result [...] [ELSE result] END",
    description: "Multi-branch conditional. Without an ELSE, an unmatched row yields NULL.",
    example: "SELECT CASE WHEN score >= 90 THEN 'A' WHEN score >= 80 THEN 'B' ELSE 'F' END FROM results;",
    aliases: ["switch", "when then", "if else"],
  },
  {
    name: "IFNULL",
    category: "Control Flow",
    syntax: "IFNULL(expr1, expr2)",
    description: "Returns expr1 if it is not NULL, otherwise expr2. Two-argument form of COALESCE.",
    example: "SELECT IFNULL(nickname, name) FROM users;",
    aliases: ["null default", "nvl", "isnull"],
  },
  {
    name: "COALESCE",
    category: "Control Flow",
    syntax: "COALESCE(value1, value2, ...)",
    description: "First non-NULL value in the list, or NULL if all are NULL.",
    example: "SELECT COALESCE(mobile, home, 'no phone') FROM contacts;",
    aliases: ["first non null", "fallback", "default value"],
  },
  {
    name: "NULLIF",
    category: "Control Flow",
    syntax: "NULLIF(expr1, expr2)",
    description: "Returns NULL if the two expressions are equal, otherwise expr1. Handy to guard against divide-by-zero.",
    example: "SELECT total / NULLIF(count, 0) FROM stats;",
    aliases: ["divide by zero", "avoid division error"],
  },

  // ------------------------------------------------------------------ JSON
  {
    name: "JSON_EXTRACT",
    category: "JSON",
    syntax: "JSON_EXTRACT(json_doc, path[, path] ...)\ncol -> '$.key'",
    description: "Extracts data at the given path. The -> operator is shorthand. Result keeps its JSON quoting — use ->> or JSON_UNQUOTE to get a plain string.",
    example: "SELECT JSON_EXTRACT('{\"a\": 1}', '$.a'), data->'$.name' FROM docs;",
    result: "1",
    aliases: ["json path", "get json key", "->"],
  },
  {
    name: "JSON_UNQUOTE",
    category: "JSON",
    syntax: "JSON_UNQUOTE(json_val)\ncol ->> '$.key'",
    description: "Strips the surrounding quotes from a JSON string value. col->>'$.k' is shorthand for JSON_UNQUOTE(JSON_EXTRACT(col, '$.k')).",
    example: "SELECT data->>'$.name' FROM docs;",
    result: "'Jane' not '\"Jane\"'",
    aliases: ["->>", "unquote", "json to string"],
  },
  {
    name: "JSON_SET",
    category: "JSON",
    syntax: "JSON_SET(json_doc, path, val[, path, val] ...)",
    description: "Inserts or updates values at the given paths — replaces if the path exists, adds if it does not.",
    example: "UPDATE docs SET data = JSON_SET(data, '$.name', 'Jane');",
    aliases: ["update json", "upsert json key"],
  },
  {
    name: "JSON_INSERT",
    category: "JSON",
    syntax: "JSON_INSERT(json_doc, path, val[, path, val] ...)",
    description: "Adds values only at paths that do NOT already exist. Existing paths are left alone.",
    example: "SELECT JSON_INSERT('{\"a\": 1}', '$.b', 2);",
    result: "'{\"a\": 1, \"b\": 2}'",
  },
  {
    name: "JSON_REPLACE",
    category: "JSON",
    syntax: "JSON_REPLACE(json_doc, path, val[, path, val] ...)",
    description: "Replaces values only at paths that already exist.",
    example: "SELECT JSON_REPLACE('{\"a\": 1}', '$.a', 9, '$.b', 2);",
    result: "'{\"a\": 9}'",
  },
  {
    name: "JSON_REMOVE",
    category: "JSON",
    syntax: "JSON_REMOVE(json_doc, path[, path] ...)",
    description: "Removes data at the given paths.",
    example: "SELECT JSON_REMOVE('{\"a\": 1, \"b\": 2}', '$.b');",
    result: "'{\"a\": 1}'",
    aliases: ["delete json key"],
  },
  {
    name: "JSON_OBJECT",
    category: "JSON",
    syntax: "JSON_OBJECT([key, val[, key, val] ...])",
    description: "Builds a JSON object from key/value pairs.",
    example: "SELECT JSON_OBJECT('id', id, 'name', name) FROM users;",
    result: "'{\"id\": 1, \"name\": \"Jane\"}'",
    aliases: ["build json", "row to json"],
  },
  {
    name: "JSON_ARRAY",
    category: "JSON",
    syntax: "JSON_ARRAY([val[, val] ...])",
    description: "Builds a JSON array from the arguments.",
    example: "SELECT JSON_ARRAY(1, 'two', NULL);",
    result: "'[1, \"two\", null]'",
  },
  {
    name: "JSON_CONTAINS",
    category: "JSON",
    syntax: "JSON_CONTAINS(target, candidate[, path])",
    description: "Returns 1 if candidate is contained in target. Remember the candidate must itself be valid JSON ('\"x\"' for a string).",
    example: "SELECT JSON_CONTAINS(tags, '\"sql\"', '$');",
    result: "1",
    aliases: ["json includes", "array contains"],
  },
  {
    name: "JSON_CONTAINS_PATH",
    category: "JSON",
    syntax: "JSON_CONTAINS_PATH(json_doc, one_or_all, path[, path] ...)",
    description: "Returns 1 if the document contains the path(s). one_or_all is 'one' or 'all'.",
    example: "SELECT JSON_CONTAINS_PATH('{\"a\": 1}', 'one', '$.a');",
    result: "1",
    aliases: ["json key exists"],
  },
  {
    name: "JSON_KEYS",
    category: "JSON",
    syntax: "JSON_KEYS(json_doc[, path])",
    description: "Top-level keys of a JSON object, as a JSON array.",
    example: "SELECT JSON_KEYS('{\"a\": 1, \"b\": 2}');",
    result: "'[\"a\", \"b\"]'",
  },
  {
    name: "JSON_LENGTH",
    category: "JSON",
    syntax: "JSON_LENGTH(json_doc[, path])",
    description: "Number of elements in an array or keys in an object. Scalars have length 1.",
    example: "SELECT JSON_LENGTH('[1, 2, 3]');",
    result: "3",
    aliases: ["json count", "array size"],
  },
  {
    name: "JSON_TYPE",
    category: "JSON",
    syntax: "JSON_TYPE(json_val)",
    description: "Type of the JSON value: OBJECT, ARRAY, STRING, INTEGER, BOOLEAN, NULL, etc.",
    example: "SELECT JSON_TYPE('[1]');",
    result: "'ARRAY'",
  },
  {
    name: "JSON_VALID",
    category: "JSON",
    syntax: "JSON_VALID(val)",
    description: "Returns 1 if the value is valid JSON. Useful in a CHECK constraint or to find bad rows in a text column.",
    example: "SELECT id FROM logs WHERE NOT JSON_VALID(payload);",
    aliases: ["is json", "validate json"],
  },
  {
    name: "JSON_TABLE",
    category: "JSON",
    syntax: "JSON_TABLE(expr, path COLUMNS (col type PATH json_path, ...)) [AS] alias",
    description: "Expands a JSON array into relational rows so you can JOIN against it.",
    example:
      "SELECT t.* FROM docs, JSON_TABLE(docs.tags, '$[*]' COLUMNS (tag VARCHAR(50) PATH '$')) AS t;",
    aliases: ["explode json", "json to rows", "unnest", "lateral"],
  },
  {
    name: "JSON_MERGE_PATCH",
    category: "JSON",
    syntax: "JSON_MERGE_PATCH(json_doc, json_doc[, json_doc] ...)",
    description: "RFC 7386 merge — later members override earlier ones. Use JSON_MERGE_PRESERVE to keep both instead.",
    example: "SELECT JSON_MERGE_PATCH('{\"a\": 1}', '{\"a\": 2, \"b\": 3}');",
    result: "'{\"a\": 2, \"b\": 3}'",
    aliases: ["merge json", "json_merge_preserve"],
  },
  {
    name: "JSON_SEARCH",
    category: "JSON",
    syntax: "JSON_SEARCH(json_doc, one_or_all, search_str[, escape_char[, path]])",
    description: "Returns the path(s) to a string value inside the document. Supports LIKE wildcards.",
    example: "SELECT JSON_SEARCH('{\"a\": \"x\"}', 'one', 'x');",
    result: "'\"$.a\"'",
    aliases: ["find json value", "json path of"],
  },
  {
    name: "JSON_PRETTY",
    category: "JSON",
    syntax: "JSON_PRETTY(json_val)",
    description: "Pretty-prints a JSON document with indentation.",
    example: "SELECT JSON_PRETTY(data) FROM docs;",
    aliases: ["format json", "indent"],
  },

  // ------------------------------------------------------------------ Cast
  {
    name: "CAST",
    category: "Cast",
    syntax: "CAST(expr AS type)",
    description:
      "Converts a value to another type. Types: BINARY, CHAR[(N)], DATE, DATETIME, TIME, DECIMAL[(M[,D])], SIGNED, UNSIGNED, JSON, DOUBLE, FLOAT, YEAR. Note it is SIGNED/UNSIGNED, not INT.",
    example: "SELECT CAST('123' AS SIGNED), CAST(price AS DECIMAL(10,2));",
    result: "123",
    aliases: ["convert type", "to int", "to string", "typecast"],
  },
  {
    name: "CONVERT",
    category: "Cast",
    syntax: "CONVERT(expr, type)\nCONVERT(expr USING charset)",
    description: "Same conversions as CAST with different syntax; the USING form converts between character sets.",
    example: "SELECT CONVERT('abc' USING utf8mb4);",
    aliases: ["charset", "collation", "encoding"],
  },
  {
    name: "BINARY",
    category: "Cast",
    syntax: "BINARY expr  -- or CAST(expr AS BINARY)",
    description: "Casts to a binary string, which forces a byte-by-byte, case-SENSITIVE comparison.",
    example: "SELECT * FROM users WHERE BINARY name = 'Jane';",
    aliases: ["case sensitive compare"],
  },

  // ------------------------------------------------------------ Encryption
  {
    name: "MD5",
    category: "Encryption",
    syntax: "MD5(str)",
    description: "128-bit MD5 hash as a 32-character hex string. Not suitable for passwords.",
    example: "SELECT MD5('abc');",
    result: "'900150983cd24fb0d6963f7d28e17f72'",
    aliases: ["hash", "checksum"],
  },
  {
    name: "SHA1",
    category: "Encryption",
    syntax: "SHA1(str)",
    description: "160-bit SHA-1 hash as a 40-character hex string. Considered weak — prefer SHA2.",
    example: "SELECT SHA1('abc');",
    aliases: ["sha", "hash"],
  },
  {
    name: "SHA2",
    category: "Encryption",
    syntax: "SHA2(str, hash_length)",
    description: "SHA-2 hash. hash_length is 224, 256, 384, 512, or 0 (= 256).",
    example: "SELECT SHA2('abc', 256);",
    aliases: ["sha256", "sha512", "hash"],
  },
  {
    name: "UUID",
    category: "Encryption",
    syntax: "UUID()",
    description: "Generates a version-1 UUID as a 36-character string.",
    example: "SELECT UUID();",
    result: "'f47ac10b-58cc-4372-a567-0e02b2c3d479'",
    aliases: ["guid", "unique id", "uuid_short"],
  },
  {
    name: "AES_ENCRYPT",
    category: "Encryption",
    syntax: "AES_ENCRYPT(str, key_str[, init_vector])",
    description: "AES-encrypts a string, returning a binary string. Decrypt with AES_DECRYPT using the same key and IV.",
    example: "SELECT HEX(AES_ENCRYPT('secret', 'key'));",
    aliases: ["aes_decrypt", "encrypt"],
  },
  {
    name: "RANDOM_BYTES",
    category: "Encryption",
    syntax: "RANDOM_BYTES(len)",
    description: "Cryptographically secure random bytes (1–1024). Good for tokens and salts.",
    example: "SELECT HEX(RANDOM_BYTES(16));",
    aliases: ["random token", "salt", "secure random"],
  },
  {
    name: "COMPRESS",
    category: "Encryption",
    syntax: "COMPRESS(string_to_compress)",
    description: "Compresses a string into a binary string. Reverse with UNCOMPRESS.",
    example: "SELECT LENGTH(COMPRESS(REPEAT('a', 1000)));",
    result: "21",
    aliases: ["uncompress", "zip", "gzip"],
  },

  // ----------------------------------------------------------- Information
  {
    name: "DATABASE",
    category: "Information",
    syntax: "DATABASE()",
    description: "Name of the current default database, or NULL if none is selected. Alias: SCHEMA().",
    example: "SELECT DATABASE();",
    aliases: ["schema", "current database"],
  },
  {
    name: "USER",
    category: "Information",
    syntax: "USER()  -- or CURRENT_USER()",
    description: "USER() is the user/host you connected as; CURRENT_USER() is the account the server matched for privileges. They can differ.",
    example: "SELECT USER(), CURRENT_USER();",
    result: "'root@localhost'",
    aliases: ["current_user", "session_user", "whoami"],
  },
  {
    name: "VERSION",
    category: "Information",
    syntax: "VERSION()",
    description: "Server version string.",
    example: "SELECT VERSION();",
    result: "'8.4.0'",
  },
  {
    name: "LAST_INSERT_ID",
    category: "Information",
    syntax: "LAST_INSERT_ID()\nLAST_INSERT_ID(expr)",
    description: "The AUTO_INCREMENT value generated by the most recent INSERT on this connection. For a multi-row INSERT it returns the FIRST id generated.",
    example: "INSERT INTO users (name) VALUES ('Jane'); SELECT LAST_INSERT_ID();",
    aliases: ["insert id", "auto_increment", "identity"],
  },
  {
    name: "ROW_COUNT",
    category: "Information",
    syntax: "ROW_COUNT()",
    description: "Rows changed/inserted/deleted by the previous statement. Returns -1 for SELECT.",
    example: "SELECT ROW_COUNT();",
    aliases: ["affected rows"],
  },
  {
    name: "CONNECTION_ID",
    category: "Information",
    syntax: "CONNECTION_ID()",
    description: "Connection (thread) ID for the current session — the value you pass to KILL.",
    example: "SELECT CONNECTION_ID();",
    aliases: ["thread id", "kill"],
  },
];
